[workspace]
members = ["dev", "slm"]
resolver = "2"

[package]
name = "slmlib"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
description = "Straight line missions utilities"
readme = "README.md"
repository = "https://github.com/barbagus/slmlib"

[lib]
name = "slmlib"
path = "src/lib.rs"

[dependencies.xml]
version = "0.8.20"
optional = true

[features]
csv=[]
gpx=["dep:xml"]
default=["csv", "gpx"]

[dev-dependencies]
approx = "0.5.1"
dev = {path = "dev"}
