[package]
name = "slm"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
license-file = "COPYING.txt"

[lib]
name = "slmlib"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0.210", features = ["derive"]}
serde_json = {version = "1.0.128"}

[dev-dependencies]
approx = "0.5.1"

[[example]]
name = "compare_scores"
