[package]
name = "dev"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version="1.0.214", features = ["derive"]}
serde_json = "1.0.132"
slmlib = {path = "../"}

[lib]
name = "dev"
path = "src/lib.rs"

[[bin]]
name = "compare_scores"
path = "src/compare_scores.rs"
