[package]
name = "dev"
version = "0.1.0"
edition = "2021"

[dependencies]
slmlib = {path = "../"}
files = {path = "../files", features=["sml", "fix"]}


[[bin]]
name = "compare_scores"
path = "src/compare_scores.rs"

[[bin]]
name = "sml_2_csv"
path = "src/sml_2_csv.rs"
